steps:
  qiniu:
    image: pcit/qiniu
    with:
      access_key: ${QINIUYUN_ACCESS_KEY}
      secret_key: ${QINIUYUN_SECRET_KEY}
      bucket: ${QINIUYUN_BUCKET}
      endpoint: ${QINIUYUN_ENDPOINT}
      files:
      - composer.json
      - Dockerfile

  qiniu_obj:
    image: pcit/qiniu
    with:
      access_key: ${QINIUYUN_ACCESS_KEY}
      secret_key: ${QINIUYUN_SECRET_KEY}
      bucket: ${QINIUYUN_BUCKET}
      endpoint: ${QINIUYUN_ENDPOINT}
      files:
        composer.json: dist.composer.json
        Dockerfile: dist.Dockerfile
