steps:
  qiniu:
    image: pcit/qiniu
    settings:
      access_key: ${QINIUYUN_ACCESS_KEY}
      secret_key: ${QINIUYUN_SECRET_KEY}
      bucket: ${QINIUYUN_BUCKET}
      endpoint: ${QINIUYUN_ENDPOINT}
      files:
      - composer.json
      - Dockerfile
  qiniu_2:
    image: pcit/qiniu
    settings:
      access_key: ${QINIUYUN_ACCESS_KEY}
      secret_key: ${QINIUYUN_SECRET_KEY}
      bucket: ${QINIUYUN_BUCKET}
      endpoint: ${QINIUYUN_ENDPOINT}
      files:
        composer.json: composer.json.dist
        Dockerfile: Dockerfile.dist
